# This is a basic workflow to help you get started with Actions

name: WTH-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - '**/deployDev.yml'
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      # Azure Login with Service Principal   
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true
          
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Resource Group Name ${{ secrets.RESOURCEGROUPNAME }}
       
      #  Create and Deploy App with ARM Deploy 
      - name: ARM Deploy
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: WTH-DevOpswithGitHub
          template: ArmTemplates/container-webapp-template-dev.json
          
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Deployment Finished!
